services:
  - type: web
    name: n8n-server
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: NODE_ENV
        value: production
      - key: GENERIC_TIMEZONE
        value: Asia/Kolkata
      - key: N8N_ENCRYPTION_KEY
        value: uRcc17PyOvhscaPoKudfppzs4EmJEYYEJxXqIqnoF5I
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: tilak
      - key: N8N_BASIC_AUTH_PASSWORD
        value: O9NGYCqhZFXZVj6EeVLPb2U9qeo2ZBad
      - key: N8N_EDITOR_BASE_URL
        value: https://YOUR-RENDER-URL.onrender.com
      - key: WEBHOOK_URL
        value: https://YOUR-RENDER-URL.onrender.com
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 5
